#!/usr/bin/env -S uv run --script
# /// script
# dependencies = [
# "rich", "uproot", "numpy", "awkward",
# "numba", "pyarrow", "click"
# ]
# ///

"""Convert an ATLAS {{INPUT_FORMAT}} DAOD to Parquet folders.

Generated by ATLAS/ntuple-wizard.html.
{{INPUT_NOTE}}
"""

import re
import shutil
from pathlib import Path

import awkward as ak
import click
import numba as nb
import numpy as np
import uproot as up
from rich import print

POINT = "[green][b]‣[/b][/green]"
INPUT_FORMAT = "{{INPUT_FORMAT}}"
OBJECTS = {{OBJECTS}}

JET_LINK_ALIASES = {
    "constLinks": (
        "AntiKt4EMPFlowJetsAuxDyn."
        "constituentLinks"
    ),
    "trackLinks": "AnalysisJetsAuxDyn.GhostTrack",
}


def selected_aliases(name):
    return dict(OBJECTS[name]["aliases"])


def make_idx(arr):
    ndim = arr.ndim
    counts = []
    for i in range(0, ndim):
        try:
            sizes = ak.num(arr, axis=-1 - i)
            counts.append(ak.flatten(sizes, axis=None))
        except Exception:
            # The outermost dimension is never read.
            pass
    idx = ak.local_index(ak.flatten(arr, axis=None))
    for _ in range(1, ndim):
        idx = ak.unflatten(idx, counts.pop(0))
    return idx


def rec_flatten(arr):
    flat = arr
    for _ in range(1, arr.ndim):
        flat = ak.flatten(flat, axis=-1)
    return flat


def first_field(record):
    fields = ak.fields(record)
    if not fields:
        raise ValueError("No variables selected")
    return record[fields[0]]


def select_per_jet(base, indexer):
    @nb.jit
    def process(
        builder: ak.ArrayBuilder,
        values: ak.Array,
        links: ak.Array,
    ):
        for values_evt, links_evt in zip(values, links):
            builder.begin_list()
            for links_jet in links_evt:
                builder.begin_list()
                for link in links_jet:
                    builder.append(values_evt[link])
                builder.end_list()
            builder.end_list()
        return builder

    selected = {}
    for name, values in ak.unzip(base, how=dict).items():
        builder = ak.ArrayBuilder()
        result = process(builder, values, indexer)
        selected[name] = result.snapshot()
    return ak.zip(selected)


def split_constituent_aliases():
    charged = {}
    neutral = {}
    for name, branches in selected_aliases("Const").items():
        charged[name] = branches[0]
        neutral[name] = branches[1]
    return charged, neutral


INDEX_FILE_BITS = 16
INDEX_LOCAL_BITS = 64 - INDEX_FILE_BITS
MAX_FILE_NUMBER = (1 << INDEX_FILE_BITS) - 1
MAX_LOCAL_INDEX = (1 << INDEX_LOCAL_BITS) - 1


def partition_from_filename(input_path):
    pattern = re.compile(
        r"^DAOD_[^.]+\.(?P<tid>\d+)\._(?P<file_number>\d+)"
        r"\.pool\.root(?:\.\d+)?$"
    )
    match = pattern.match(input_path.name)
    if not match:
        raise click.ClickException(
            "Input filename must look like "
            "DAOD_PHYSLITE.37620644._000244.pool.root[.N] "
            "so tid and fileNumber partitions can be derived"
        )
    file_number = int(match.group("file_number"))
    if file_number > MAX_FILE_NUMBER:
        raise click.ClickException(
            f"File number {file_number} exceeds the {MAX_FILE_NUMBER} "
            "maximum that can be encoded in 16 index bits"
        )
    return {
        "tid": match.group("tid"),
        "fileNumber": file_number,
    }


def encode_global_index(local_index, file_number, label):
    flattened = ak.flatten(local_index, axis=None)
    if len(flattened) > 0 and int(ak.max(flattened)) > MAX_LOCAL_INDEX:
        raise click.ClickException(
            f"{label} local index exceeds {MAX_LOCAL_INDEX}; cannot reserve "
            "the leading 16 bits for the file number"
        )
    prefix = np.uint64(file_number << INDEX_LOCAL_BITS)
    return ak.values_astype(local_index, np.uint64) + prefix


def make_global_idx(arr, file_number, label):
    return encode_global_index(make_idx(arr), file_number, label)



def selected_output_partition_paths(output, partition):
    tid_dir = f"tid={partition['tid']}"
    file_dir = f"fileNumber={partition['fileNumber']}"
    return [
        output / config["folder"] / tid_dir / file_dir
        for config in OBJECTS.values()
    ]


def existing_output_partitions(output, partition):
    if not output.exists():
        return []
    return [path for path in selected_output_partition_paths(output, partition) if path.exists()]


def cleanup_output_partitions(output, partition):
    tid_dir = f"tid={partition['tid']}"
    file_dir = f"fileNumber={partition['fileNumber']}"
    if not output.exists():
        return
    for target in selected_output_partition_paths(output, partition):
        if target.exists():
            shutil.rmtree(target)
        tid_path = target.parent
        try:
            tid_path.rmdir()
        except OSError:
            pass

def write_object(output, folder, partition, payload, flatten=True):
    path = (
        output
        / folder
        / f"tid={partition['tid']}"
        / f"fileNumber={partition['fileNumber']}"
    )
    if path.exists():
        raise click.ClickException(f"Output partition exists: {path}")
    path.mkdir(parents=True)
    data = rec_flatten(payload) if flatten else payload
    ak.to_parquet(data, path / "data.parquet")


@click.command()
@click.argument(
    "input",
    type=click.Path(
        exists=True,
        dir_okay=False,
        resolve_path=True,
        path_type=Path,
    ),
    required=True,
)
@click.option(
    "-o",
    "--output",
    type=click.Path(
        exists=False,
        dir_okay=True,
        file_okay=False,
        path_type=Path,
    ),
    required=True,
)
@click.option(
    "--skip-unreadable/--fail-unreadable",
    default=True,
    show_default=True,
    help="Skip unreadable or truncated ROOT inputs instead of failing the job.",
)
@click.option(
    "--skip-existing/--fail-existing",
    default=True,
    show_default=True,
    help="Skip inputs whose selected output partitions already exist, allowing safe job reruns.",
)
def ntuple_maker(input, output, skip_unreadable, skip_existing):
    partition = partition_from_filename(input)
    existing_partitions = existing_output_partitions(output, partition)
    if existing_partitions:
        paths = ", ".join(str(path) for path in existing_partitions[:3])
        suffix = "" if len(existing_partitions) <= 3 else f", and {len(existing_partitions) - 3} more"
        message = f"Output partition exists for {input}: {paths}{suffix}"
        if skip_existing:
            click.echo(f"WARNING: skipping existing output partition: {message}", err=True)
            return
        raise click.ClickException(message)

    try:
        with up.open(input) as file:
            tree = file["CollectionTree"]
            aliases = {
                name: selected_aliases(name)
                for name in OBJECTS
            }

            if "Const" in OBJECTS:
                const_aliases = split_constituent_aliases()
                aliases["c_const"] = const_aliases[0]
                aliases["n_const"] = const_aliases[1]
                aliases["Jet"] = {
                    **aliases.get("Jet", {}),
                    "__jetIndexSource": "AnalysisJetsAuxDyn.pt",
                    "constLinks": JET_LINK_ALIASES["constLinks"],
                }
            if "Track" in OBJECTS:
                aliases["Jet"] = {
                    **aliases.get("Jet", {}),
                    "__jetIndexSource": "AnalysisJetsAuxDyn.pt",
                    "trackLinks": JET_LINK_ALIASES["trackLinks"],
                }

            arrays = {
                name: tree.arrays(
                    expressions=object_aliases.keys(),
                    aliases=object_aliases,
                )
                for name, object_aliases in aliases.items()
                if object_aliases
            }

            event = arrays["Event"]
            if len(event) == 0:
                raise click.ClickException("No events found")

            print(f"{POINT} Read {len(event)} events")
            event_index = make_global_idx(
                first_field(event),
                partition["fileNumber"],
                "eventIndex",
            )
            output.mkdir(parents=True, exist_ok=True)

            if "Event" in OBJECTS:
                print(f"  {POINT} Events")
                event_payload = {"eventIndex": event_index}
                event_payload.update(ak.unzip(event, how=dict))
                write_object(
                    output,
                    OBJECTS["Event"]["folder"],
                    partition,
                    ak.zip(event_payload),
                )

            jet_index = None
            jet = arrays.get("Jet")
            if jet is not None:
                jet_index_source = (
                    jet["__jetIndexSource"]
                    if "__jetIndexSource" in ak.fields(jet)
                    else first_field(jet)
                )
                jet_index = make_global_idx(
                    jet_index_source,
                    partition["fileNumber"],
                    "jetIndex",
                )
                if "Jet" in OBJECTS:
                    print(f"  {POINT} Jets")
                    jet_payload = {
                        "jetIndex": jet_index,
                        "eventIndex": event_index,
                    }
                    jet_payload.update(
                        {
                            name: jet[name]
                            for name in selected_aliases("Jet")
                        }
                    )
                    write_object(
                        output,
                        OBJECTS["Jet"]["folder"],
                        partition,
                        ak.zip(jet_payload),
                    )

            if "Const" in OBJECTS:
                print(f"  {POINT} Following constituent links")
                hashes, counts = np.unique(
                    ak.flatten(
                        jet.constLinks.m_persKey[0],
                        axis=None,
                    ),
                    return_counts=True,
                )
                charged_fields = ak.fields(arrays["c_const"])
                neutral_fields = ak.fields(arrays["n_const"])
                charged_count = len(
                    arrays["c_const"][0][charged_fields[0]]
                )
                neutral_count = len(
                    arrays["n_const"][0][neutral_fields[0]]
                )
                if len(hashes) < 2:
                    raise click.ClickException(
                        "Cannot identify charged/neutral hashes"
                    )
                charged_first = charged_count == counts[0]
                neutral_second = neutral_count == counts[1]
                charged_second = charged_count == counts[1]
                neutral_first = neutral_count == counts[0]
                if charged_first and neutral_second:
                    charged_hash = hashes[0]
                    neutral_hash = hashes[1]
                elif charged_second and neutral_first:
                    charged_hash = hashes[1]
                    neutral_hash = hashes[0]
                else:
                    raise click.ClickException(
                        "Constituent counts do not match hashes"
                    )
                charged = select_per_jet(
                    arrays["c_const"],
                    jet.constLinks.m_persIndex[
                        jet.constLinks.m_persKey == charged_hash
                    ],
                )
                neutral = select_per_jet(
                    arrays["n_const"],
                    jet.constLinks.m_persIndex[
                        jet.constLinks.m_persKey == neutral_hash
                    ],
                )
                constituents = ak.concatenate(
                    [charged, neutral],
                    axis=2,
                )
                const_index = make_global_idx(
                    first_field(constituents),
                    partition["fileNumber"],
                    "constIndex",
                )
                const_payload = {
                    "constIndex": const_index,
                    "jetIndex": jet_index,
                    "eventIndex": event_index,
                }
                const_fields = ak.unzip(constituents, how=dict)
                const_payload.update(const_fields)
                print(f"  {POINT} Constituents")
                write_object(
                    output,
                    OBJECTS["Const"]["folder"],
                    partition,
                    ak.zip(const_payload),
                )

            if "Track" in OBJECTS:
                print(f"  {POINT} Following track ElementLinks")
                tracks = select_per_jet(
                    arrays["Track"],
                    jet.trackLinks.m_persIndex[
                        jet.trackLinks.m_persKey != 0
                    ],
                )
                track_index = make_global_idx(
                    first_field(tracks),
                    partition["fileNumber"],
                    "trackIndex",
                )
                track_payload = {
                    "trackIndex": track_index,
                    "jetIndex": jet_index,
                    "eventIndex": event_index,
                }
                track_payload.update(ak.unzip(tracks, how=dict))
                print(f"  {POINT} Tracks")
                write_object(
                    output,
                    OBJECTS["Track"]["folder"],
                    partition,
                    ak.zip(track_payload),
                )

            simple_objects = (
                "LargeRJet",
                "Electron",
                "Muon",
                "Photon",
            )
            for name in simple_objects:
                if name not in OBJECTS:
                    continue
                record = arrays[name]
                object_index = make_global_idx(
                    first_field(record),
                    partition["fileNumber"],
                    OBJECTS[name]["index_name"],
                )
                payload = {
                    OBJECTS[name]["index_name"]: object_index,
                    "eventIndex": event_index,
                }
                payload.update(ak.unzip(record, how=dict))
                print(f"  {POINT} {OBJECTS[name]['folder']}")
                write_object(
                    output,
                    OBJECTS[name]["folder"],
                    partition,
                    ak.zip(payload),
                )

            if "MET" in OBJECTS:
                print(f"  {POINT} MET")
                met_payload = {"eventIndex": event_index}
                met_fields = ak.unzip(arrays["MET"], how=dict)
                met_payload.update(met_fields)
                write_object(
                    output,
                    OBJECTS["MET"]["folder"],
                    partition,
                    ak.zip(met_payload),
                    flatten=False,
                )

            print(f"{POINT} DONE")
    except (OSError, up.exceptions.KeyInFileError) as error:
        if skip_unreadable:
            cleanup_output_partitions(output, partition)
            click.echo(f"WARNING: skipping unreadable input {input}: {error}", err=True)
            return
        raise click.ClickException(f"Cannot read input ROOT file {input}: {error}") from error


if __name__ == "__main__":
    ntuple_maker()
